--1)
SELECT *
FROM VOL
WHERE HD BETWEEN 12 AND 14 AND VD='PARIS'
--2)
SELECT *
FROM PILOTE
WHERE PILNOM LIKE 'S_%'

INSERT INTO PILOTE
VALUES ('S', 'NICE')

DELETE FROM PILOTE
WHERE PILNOM='S'
--3)
SELECT COUNT(AV)as [NB AVION],MAX(CAP) as[CAPACITE MAX.],MIN(CAP) as [CAPACITE MIN.], LOC
FROM AVION 
GROUP BY LOC 
--4)
SELECT LOC,AVG(CAP) as [MOYENNE],AVMARQ,COUNT(*) FROM AVION GROUP BY LOC,AVMARQ
--5)
SELECT LOC,AVG(CAP) as [MOYENNE],COUNT(*) FROM AVION GROUP BY LOC HAVING COUNT(*)>1
--6)
SELECT PILNOM FROM PILOTE WHERE ADR in (SELECT LOC FROM AVION WHERE AVMARQ='AIRBUS')
--7)
SELECT DISTINCT PILNOM FROM PILOTE,VOL WHERE PILOTE.PIL =VOL.PIL AND VOL.AV in 
(SELECT VOL.AV FROM AVION,VOL WHERE AVION.AV=VOL.AV AND AVION.AVMARQ='AIRBUS')
AND PILOTE.ADR in(SELECT LOC FROM AVION WHERE AVMARQ='AIRBUS')
--7.1
SELECT DISTINCT PILNOM FROM PILOTE,VOL,AVION WHERE AVION.AVMARQ='AIRBUS'
AND AVION.LOC=PILOTE.ADR
AND PILOTE.PIL=VOL.PIL
AND VOL.AV=AVION.AV

--8
--8	Quels sont les noms des pilotes qui conduisent un Airbus 
--ou qui habitent dans la ville de localisation d'un Airbus ?
SELECT DISTINCT PILNOM FROM PILOTE,VOL WHERE PILOTE.PIL =VOL.PIL AND VOL.AV in 
(SELECT VOL.AV FROM AVION,VOL WHERE AVION.AV=VOL.AV AND AVION.AVMARQ='AIRBUS')
or PILOTE.ADR in(SELECT LOC FROM AVION WHERE AVMARQ='AIRBUS')

--9	Quels sont les noms des pilotes qui conduisent un Airbus 
--sauf ceux qui habitent dans la ville de localisation d'un Airbus ?
SELECT DISTINCT PILNOM FROM PILOTE,VOL WHERE PILOTE.PIL =VOL.PIL AND VOL.AV in 
(SELECT VOL.AV FROM AVION,VOL WHERE AVION.AV=VOL.AV AND AVION.AVMARQ='AIRBUS')
AND PILOTE.ADR NOT in(SELECT LOC FROM AVION WHERE AVMARQ='AIRBUS')

SELECT distinct PILNOM
FROM PILOTE,AVION,VOL
WHERE VOL.PIL=PILOTE.PIL and VOL.AV=AVION.AV AND  AVION.AVMARQ='AIRBUS' AND PILOTE.ADR<>AVION.LOC;

SELECT distinct PILNOM
FROM PILOTE
INNER JOIN VOL
ON VOL.PIL=PILOTE.PIL
INNER JOIN AVION
ON VOL.AV=AVION.AV
WHERE AVION.AVMARQ='AIRBUS' AND PILOTE.ADR<>AVION.LOC;


--10	Quels sont les vols ayant un trajet identique ( VD, VA ) à ceux assurés par Serge ?


SELECT VD,VA
FROM VOL,PILOTE
WHERE VOL.PIL=PILOTE.PIL AND VD IN
(SELECT VD
FROM VOL,PILOTE
WHERE VOL.PIL=PILOTE.PIL AND PILOTE.PILNOM='SERGE')
AND VA IN
(SELECT VA
FROM VOL,PILOTE
WHERE VOL.PIL=PILOTE.PIL AND PILOTE.PILNOM='SERGE')
AND PILOTE.PILNOM <> 'SERGE'


--11	Donner toutes les paires de pilotes habitant la même ville ( sans doublon ).
SELECT P1.PILNOM, P2.PILNOM
FROM PILOTE P1, PILOTE P2
WHERE P1.ADR=P2.ADR AND P1.PILNOM < P2.PILNOM

--12	Quels sont les noms des pilotes qui conduisent un avion que conduit aussi le pilote n°1 ?
SELECT PILOTE.PILNOM, VOL.AV
FROM PILOTE
INNER JOIN VOL
ON PILOTE.PIL = VOL.PIL
WHERE VOL.AV IN (
	SELECT VOL.AV
	FROM VOL
	WHERE VOL.PIL = 1
) AND PILOTE.PIL <> 1

--13	Donner toutes les paires de villes telles qu'un avion localisé dans la ville de départ soit
-- conduit par un pilote résidant dans la ville d'arrivée.

SELECT VOL.VD, VOL.VA
FROM PILOTE
INNER JOIN VOL 
ON PILOTE.PIL = VOL.PIL
INNER JOIN AVION
ON AVION.AV = VOL.AV
WHERE AVION.LOC = VOL.VD AND PILOTE.ADR = VOL.VA

--14	Sélectionner les numéros des pilotes qui conduisent tous les Airbus ?

SELECT distinct PILOTE.PIL, PILOTE.PILNOM
FROM PILOTE
WHERE (
	SELECT COUNT(*)
	FROM AVION
	WHERE AVMARQ = 'AIRBUS'
) = (
	SELECT COUNT(*)
	FROM VOL
	INNER JOIN AVION
	ON VOL.AV = AVION.AV
	WHERE VOL.PIL = PILOTE.PIL AND AVMARQ = 'AIRBUS'
)


